apiVersion: postgresql.easymile.com/v1alpha1
kind: PostgresqlUser
metadata:
  name: full
spec:
  # Database link
  database:
    # Resource name
    name: simple
    # Resource namespace
    # Will use resource namespace if not set
    # namespace:
  # Generated Secret name prefix
  generatedSecretNamePrefix: secret1
  # User role prefix
  rolePrefix: pguser1
  # Privileges for user role
  privileges: OWNER
  # User password rotation duration
  # Default set to ""
  userPasswordRotationDuration: 30d
