apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: postgresqlengineconfigurations.postgresql.easymile.com
spec:
  additionalPrinterColumns:
  - JSONPath: .status.lastValidatedTime
    description: Last time validated
    name: Last Validation
    type: date
  - JSONPath: .status.phase
    description: Status phase
    name: Phase
    type: string
  - JSONPath: .metadata.creationTimestamp
    name: Age
    type: date
  group: postgresql.easymile.com
  names:
    kind: PostgresqlEngineConfiguration
    listKind: PostgresqlEngineConfigurationList
    plural: postgresqlengineconfigurations
    shortNames:
    - pgengcfg
    - pgec
    singular: postgresqlengineconfiguration
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: PostgresqlEngineConfiguration is the Schema for the postgresqlengineconfigurations
        API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: PostgresqlEngineConfigurationSpec defines the desired state
            of PostgresqlEngineConfiguration
          properties:
            checkDuration:
              description: Duration between two checks for valid engine
              type: string
            defaultDatabase:
              description: Default database
              type: string
            host:
              description: Hostname
              type: string
            port:
              description: Port
              type: integer
            provider:
              description: Provider
              enum:
              - ""
              - AWS
              - AZURE
              type: string
            secretName:
              description: User and password secret
              type: string
            uriArgs:
              description: URI args like sslmode, ...
              type: string
            waitLinkedResourcesDeletion:
              description: Wait for linked resource to be deleted
              type: boolean
          required:
          - host
          - secretName
          type: object
        status:
          description: PostgresqlEngineConfigurationStatus defines the observed state
            of PostgresqlEngineConfiguration
          properties:
            hash:
              description: Resource Spec hash
              type: string
            lastValidatedTime:
              description: Last validated time
              type: string
            message:
              description: Human-readable message indicating details about current
                operator phase or error.
              type: string
            phase:
              description: Current phase of the operator
              type: string
            ready:
              description: True if all resources are in a ready state and all work
                is done.
              type: boolean
          required:
          - phase
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
